<#
.SYNOPSIS
    EntraChecks-SOC2Reporting.psm1 - SOC 2 standalone report builder
    (HTML + Excel/CSV) for internal readiness assessments.

.DESCRIPTION
    Renders the SOC 2 audit view as a TSC-structured report distinct from the
    severity-ranked unified EntraChecks report. The HTML report supports an
    optional local "identity lookup" side panel that resolves redacted hashes
    back to UPNs when the companion identity-resolution map is co-located.

    Excel output is provided when the optional ImportExcel module is available;
    otherwise a multi-CSV fallback is produced.

.NOTES
    Version: 1.0.0
    Author: EntraChecks Project

.LINK
    SOC 2 Implementation Plan: plans/SOC2-Implementation-Plan.md
#>

#Requires -Version 5.1

$script:ModuleName = 'EntraChecks-SOC2Reporting'
$script:ModuleVersion = '1.0.0'

#region ==================== HTML REPORT ====================

function New-SOC2AuditReport {
    <#
    .SYNOPSIS
        Renders the SOC 2 standalone HTML audit report.

    .DESCRIPTION
        Produces a TSC-structured report including: cover panel, by-category
        summary, control register, per-control finding tables, manual
        attestation register, evidence summary. Supports white-label branding
        via Get-ReportBrandingContext and an optional identity-lookup side panel
        that loads the resolution map from a sibling local path (data is NOT
        embedded into the HTML).

    .PARAMETER AssessmentResult
        The PSCustomObject returned by Invoke-SOC2Assessment.

    .PARAMETER OutputPath
        Where to write the .html file.

    .PARAMETER Branding
        Optional branding context from Get-ReportBrandingContext.

    .PARAMETER IdentityResolutionMapPath
        Optional local file path to the identity-resolution-*.json. When
        provided, the report exposes an "Identity lookup" side panel.

    .OUTPUTS
        String path to the rendered HTML file.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$AssessmentResult,

        [Parameter(Mandatory)]
        [string]$OutputPath,

        [pscustomobject]$Branding,

        [string]$IdentityResolutionMapPath
    )

    if (-not $Branding) {
        if (Get-Command Get-ReportBrandingContext -ErrorAction SilentlyContinue) {
            $Branding = Get-ReportBrandingContext -Config $null -ReportTitle 'SOC 2 Internal Readiness Assessment'
        } else {
            $Branding = [pscustomobject]@{
                WhiteLabel = $false
                ReportTitle = 'SOC 2 Internal Readiness Assessment'
                OrganizationName = 'EntraChecks'
                LogoDataUri = ''
                PrimaryColor = '#005A9E'
                Footer = ''
                Attribution = "Generated by EntraChecks v$($script:ModuleVersion)"
                SuppressEntraChecksBranding = $false
            }
        }
    }

    $catalog = $AssessmentResult.Catalog
    $summary = $AssessmentResult.Summary
    $evidence = $AssessmentResult.Evidence

    $primaryColor = $Branding.PrimaryColor
    $orgName = $Branding.OrganizationName
    $title = $Branding.ReportTitle
    $logoHtml = if ($Branding.LogoDataUri) {
        "<img src='$($Branding.LogoDataUri)' alt='Logo' class='org-logo' />"
    } else { '' }

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('<!DOCTYPE html>')
    [void]$sb.AppendLine('<html lang="en">')
    [void]$sb.AppendLine('<head>')
    [void]$sb.AppendLine("<meta charset='UTF-8'>")
    [void]$sb.AppendLine("<title>$([System.Web.HttpUtility]::HtmlEncode($title))</title>")
    [void]$sb.AppendLine(@"
<style>
* { box-sizing: border-box; }
body { font-family: Segoe UI, Roboto, system-ui, sans-serif; margin: 0; color: #1a1a1a; background: #f4f6f8; }
header { background: $primaryColor; color: white; padding: 24px 32px; display: flex; align-items: center; gap: 16px; }
header .org-logo { max-height: 48px; max-width: 200px; background: white; padding: 4px; border-radius: 4px; }
header h1 { margin: 0; font-size: 1.6em; font-weight: 600; }
header .meta { margin-left: auto; text-align: right; font-size: 0.85em; opacity: 0.9; }
main { display: grid; grid-template-columns: 1fr 320px; gap: 24px; max-width: 1600px; margin: 0 auto; padding: 24px; }
section.report { background: white; border-radius: 6px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 24px; }
aside { position: sticky; top: 24px; align-self: start; }
aside .panel { background: white; border-radius: 6px; padding: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 16px; }
h2 { color: $primaryColor; border-bottom: 2px solid $primaryColor; padding-bottom: 8px; margin-top: 0; }
h3 { color: #333; margin-top: 24px; }
table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 0.9em; }
th { background: #f0f3f6; text-align: left; padding: 8px 12px; border-bottom: 2px solid #d0d5dc; }
td { padding: 8px 12px; border-bottom: 1px solid #e5e8ec; vertical-align: top; }
tr:hover { background: #fafbfc; }
.status-ok { color: #2a8c3c; font-weight: 600; }
.status-fail { color: #c8102e; font-weight: 600; }
.status-warning { color: #d89b00; font-weight: 600; }
.status-info { color: #5a6c7d; }
.status-manual { color: #5b3fa9; font-weight: 600; }
.severity-Critical { background: #c8102e; color: white; padding: 2px 8px; border-radius: 3px; font-size: 0.85em; }
.severity-High { background: #ff6f00; color: white; padding: 2px 8px; border-radius: 3px; font-size: 0.85em; }
.severity-Medium { background: #d89b00; color: white; padding: 2px 8px; border-radius: 3px; font-size: 0.85em; }
.severity-Low { background: #4a90d9; color: white; padding: 2px 8px; border-radius: 3px; font-size: 0.85em; }
.severity-Info { background: #6c757d; color: white; padding: 2px 8px; border-radius: 3px; font-size: 0.85em; }
.summary-grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin: 16px 0; }
.summary-card { background: #f8f9fb; padding: 16px; border-left: 4px solid $primaryColor; border-radius: 4px; }
.summary-card .family { font-weight: 600; font-size: 1.1em; margin-bottom: 8px; }
.summary-card .row { font-size: 0.85em; color: #555; }
.tsc-control { background: #f8f9fb; border-left: 4px solid $primaryColor; padding: 12px 16px; margin-bottom: 16px; border-radius: 4px; }
.tsc-control .id { font-weight: 700; font-size: 1.1em; color: $primaryColor; }
.tsc-control .meta { font-size: 0.85em; color: #666; margin-top: 4px; }
.tsc-control .desc { margin-top: 8px; }
footer { background: #2a3441; color: #d0d5dc; text-align: center; padding: 16px; font-size: 0.85em; }
.lookup-input { width: 100%; padding: 8px; border: 1px solid #d0d5dc; border-radius: 4px; font-family: monospace; }
.lookup-result { background: #f0f3f6; padding: 8px; margin-top: 8px; border-radius: 4px; font-family: monospace; font-size: 0.85em; word-break: break-all; }
.lookup-warning { background: #fff8e1; padding: 8px; margin-top: 8px; border-radius: 4px; font-size: 0.85em; color: #7b5e00; }
.evidence-hash { font-family: monospace; font-size: 0.85em; word-break: break-all; }
</style>
"@)
    [void]$sb.AppendLine('</head>')
    [void]$sb.AppendLine('<body>')

    # Header
    [void]$sb.AppendLine('<header>')
    [void]$sb.AppendLine($logoHtml)
    [void]$sb.AppendLine("<h1>$([System.Web.HttpUtility]::HtmlEncode($title))</h1>")
    [void]$sb.AppendLine("<div class='meta'>")
    [void]$sb.AppendLine("<div>$([System.Web.HttpUtility]::HtmlEncode($orgName))</div>")
    [void]$sb.AppendLine("<div>Generated $((Get-Date).ToString('u'))</div>")
    [void]$sb.AppendLine('</div>')
    [void]$sb.AppendLine('</header>')

    [void]$sb.AppendLine('<main>')
    [void]$sb.AppendLine('<div>')

    # Cover panel
    [void]$sb.AppendLine('<section class="report">')
    [void]$sb.AppendLine('<h2>Assessment Cover</h2>')
    [void]$sb.AppendLine('<table>')
    [void]$sb.AppendLine("<tr><th>TSC Revision</th><td>AICPA TSC 2017 (revised 2022)</td></tr>")
    [void]$sb.AppendLine("<tr><th>Type</th><td>Type 1 (point-in-time)</td></tr>")
    [void]$sb.AppendLine("<tr><th>Categories in scope</th><td>$(($catalog | Select-Object -ExpandProperty Family -Unique) -join ', ')</td></tr>")
    [void]$sb.AppendLine("<tr><th>Total controls</th><td>$($summary.TotalControls)</td></tr>")
    [void]$sb.AppendLine("<tr><th>Total findings</th><td>$($summary.TotalFindings)</td></tr>")
    if ($evidence) {
        [void]$sb.AppendLine("<tr><th>Evidence bundle hash (SHA-256)</th><td class='evidence-hash'>$($evidence.BundleHash)</td></tr>")
        [void]$sb.AppendLine("<tr><th>Evidence bundle path</th><td>$([System.Web.HttpUtility]::HtmlEncode($evidence.Directory))</td></tr>")
    }
    [void]$sb.AppendLine('</table>')
    [void]$sb.AppendLine('</section>')

    # Summary grid by family
    [void]$sb.AppendLine('<section class="report">')
    [void]$sb.AppendLine('<h2>Summary by Trust Services Category</h2>')
    [void]$sb.AppendLine('<div class="summary-grid">')
    foreach ($family in @('CC', 'A', 'C', 'PI', 'P')) {
        $f = $summary.ByFamily[$family]
        if (-not $f) { continue }
        $totalControls = $f.Automated + $f.Manual
        if ($totalControls -eq 0) { continue }
        [void]$sb.AppendLine('<div class="summary-card">')
        [void]$sb.AppendLine("<div class='family'>$family</div>")
        [void]$sb.AppendLine("<div class='row'>Controls: $totalControls (auto: $($f.Automated), manual: $($f.Manual))</div>")
        [void]$sb.AppendLine("<div class='row'><span class='status-ok'>Pass: $($f.Pass)</span></div>")
        [void]$sb.AppendLine("<div class='row'><span class='status-fail'>Fail: $($f.Fail)</span></div>")
        [void]$sb.AppendLine("<div class='row'><span class='status-warning'>Warn: $($f.Warning)</span></div>")
        [void]$sb.AppendLine("<div class='row'><span class='status-info'>Info: $($f.Info)</span></div>")
        [void]$sb.AppendLine('</div>')
    }
    [void]$sb.AppendLine('</div>')
    [void]$sb.AppendLine('</section>')

    # Control register grouped by family
    foreach ($family in @('CC', 'A', 'C', 'PI', 'P')) {
        $controlsInFamily = @($catalog | Where-Object { $_.Family -eq $family })
        if ($controlsInFamily.Count -eq 0) { continue }

        [void]$sb.AppendLine('<section class="report">')
        $familyName = ($controlsInFamily | Select-Object -First 1 -ExpandProperty FamilyName)
        [void]$sb.AppendLine("<h2>$family - $([System.Web.HttpUtility]::HtmlEncode($familyName))</h2>")

        foreach ($control in $controlsInFamily) {
            $controlFindings = @()
            if ($summary.ControlFindings.ContainsKey($control.Id)) {
                $controlFindings = @($summary.ControlFindings[$control.Id])
            }

            [void]$sb.AppendLine('<div class="tsc-control">')
            [void]$sb.AppendLine("<div class='id'>$($control.Id)</div>")
            [void]$sb.AppendLine("<div class='meta'>Automation: $($control.Automation) | Owner hint: $([System.Web.HttpUtility]::HtmlEncode($control.ControlOwnerHint)) | Findings: $($controlFindings.Count)</div>")
            [void]$sb.AppendLine("<div class='desc'>$([System.Web.HttpUtility]::HtmlEncode($control.Description))</div>")

            if ($controlFindings.Count -gt 0) {
                [void]$sb.AppendLine('<table>')
                [void]$sb.AppendLine('<thead><tr><th>Status</th><th>Severity</th><th>Object</th><th>Description</th><th>Remediation</th></tr></thead>')
                [void]$sb.AppendLine('<tbody>')
                foreach ($finding in $controlFindings) {
                    $statusClass = "status-$(($finding.Status -as [string]).ToLower())"
                    $severity = if ($finding.PSObject.Properties['Severity']) { $finding.Severity } else { 'Info' }
                    [void]$sb.AppendLine('<tr>')
                    [void]$sb.AppendLine("<td class='$statusClass'>$($finding.Status)</td>")
                    [void]$sb.AppendLine("<td><span class='severity-$severity'>$severity</span></td>")
                    [void]$sb.AppendLine("<td>$([System.Web.HttpUtility]::HtmlEncode($finding.Object))</td>")
                    [void]$sb.AppendLine("<td>$([System.Web.HttpUtility]::HtmlEncode($finding.Description))</td>")
                    [void]$sb.AppendLine("<td>$([System.Web.HttpUtility]::HtmlEncode($finding.Remediation))</td>")
                    [void]$sb.AppendLine('</tr>')
                }
                [void]$sb.AppendLine('</tbody>')
                [void]$sb.AppendLine('</table>')
            }

            [void]$sb.AppendLine('</div>')
        }
        [void]$sb.AppendLine('</section>')
    }

    [void]$sb.AppendLine('</div>')

    # Side panel
    [void]$sb.AppendLine('<aside>')
    [void]$sb.AppendLine('<div class="panel">')
    [void]$sb.AppendLine('<h3>Identity lookup</h3>')
    if ($IdentityResolutionMapPath) {
        $escapedPath = $IdentityResolutionMapPath -replace '\\', '\\\\'
        [void]$sb.AppendLine("<p style='font-size: 0.85em; color: #555;'>Resolves redacted hashes shown in this report to UPNs. Lookup data is loaded locally from the resolution map at:</p>")
        [void]$sb.AppendLine("<p style='font-family: monospace; font-size: 0.75em; word-break: break-all;'>$([System.Web.HttpUtility]::HtmlEncode($IdentityResolutionMapPath))</p>")
        [void]$sb.AppendLine("<input type='text' id='lookup-input' class='lookup-input' placeholder='Paste hash prefix (12+ chars)' />")
        [void]$sb.AppendLine("<div id='lookup-result' class='lookup-result'>Awaiting input...</div>")
        [void]$sb.AppendLine(@"
<script>
let resolutionData = null;
async function loadMap() {
  try {
    const r = await fetch('$escapedPath');
    if (!r.ok) throw new Error('HTTP ' + r.status);
    resolutionData = await r.json();
    document.getElementById('lookup-result').textContent = 'Loaded ' + resolutionData.Entries.length + ' entries.';
  } catch (e) {
    document.getElementById('lookup-result').className = 'lookup-warning';
    document.getElementById('lookup-result').textContent = 'Could not load resolution map (open this report directly from the file system, not via http://). Error: ' + e.message;
  }
}
document.addEventListener('DOMContentLoaded', loadMap);
document.addEventListener('input', (e) => {
  if (e.target.id !== 'lookup-input') return;
  if (!resolutionData) return;
  const q = (e.target.value || '').toLowerCase().trim();
  if (q.length < 8) {
    document.getElementById('lookup-result').textContent = 'Type at least 8 hex chars...';
    return;
  }
  const matches = resolutionData.Entries.filter(x => x.Hash.startsWith(q));
  if (matches.length === 0) {
    document.getElementById('lookup-result').textContent = 'No match.';
  } else {
    document.getElementById('lookup-result').innerHTML = matches.slice(0, 5).map(m =>
      'Hash: ' + m.Hash.substring(0, 16) + '...<br>UPN: ' + (m.UPN || '(none)') + '<br>Display: ' + (m.DisplayName || '(none)')
    ).join('<hr>');
  }
});
</script>
"@)
    } else {
        [void]$sb.AppendLine("<p style='font-size: 0.85em; color: #555;'>No identity-resolution map is associated with this report (redaction was not enabled, or no PII was redacted).</p>")
    }
    [void]$sb.AppendLine('</div>')

    [void]$sb.AppendLine('<div class="panel">')
    [void]$sb.AppendLine('<h3>Evidence integrity</h3>')
    if ($evidence) {
        [void]$sb.AppendLine("<p style='font-size: 0.85em;'>Bundle hash (SHA-256):</p>")
        [void]$sb.AppendLine("<p class='evidence-hash' style='font-size: 0.7em;'>$($evidence.BundleHash)</p>")
        [void]$sb.AppendLine("<p style='font-size: 0.8em;'>To verify: <code>Test-SOC2EvidenceBundle -ManifestPath '$($evidence.ManifestPath)'</code></p>")
    } else {
        [void]$sb.AppendLine("<p style='font-size: 0.85em; color: #555;'>No evidence bundle was produced.</p>")
    }
    [void]$sb.AppendLine('</div>')

    [void]$sb.AppendLine('</aside>')
    [void]$sb.AppendLine('</main>')

    [void]$sb.AppendLine('<footer>')
    if ($Branding.Footer) {
        [void]$sb.AppendLine([System.Web.HttpUtility]::HtmlEncode($Branding.Footer))
        [void]$sb.AppendLine('<br>')
    }
    if (-not $Branding.SuppressEntraChecksBranding) {
        [void]$sb.AppendLine($Branding.Attribution)
    }
    [void]$sb.AppendLine('</footer>')

    [void]$sb.AppendLine('</body>')
    [void]$sb.AppendLine('</html>')

    Add-Type -AssemblyName System.Web -ErrorAction SilentlyContinue
    Set-Content -LiteralPath $OutputPath -Value $sb.ToString() -Encoding UTF8

    return $OutputPath
}

#endregion

#region ==================== EXCEL / CSV REPORT ====================

function New-SOC2AuditWorkbook {
    <#
    .SYNOPSIS
        Renders the SOC 2 audit workbook (Excel via ImportExcel if available,
        else multi-CSV fallback).

    .DESCRIPTION
        Sheets / files emitted:
        - Cover
        - Summary by Category
        - Control Register
        - Findings - CC6, CC7, CC8, Other CC, Availability (A), Confidentiality (C)
        - Manual Attestation Register
        - Evidence Register

    .PARAMETER AssessmentResult
        The PSCustomObject returned by Invoke-SOC2Assessment.

    .PARAMETER OutputPath
        Where to write the .xlsx (or CSV directory if ImportExcel is unavailable).

    .OUTPUTS
        String path to the workbook (or directory of CSVs).
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$AssessmentResult,

        [Parameter(Mandatory)]
        [string]$OutputPath
    )

    $catalog = $AssessmentResult.Catalog
    $summary = $AssessmentResult.Summary
    $evidence = $AssessmentResult.Evidence

    $useExcel = $null -ne (Get-Module -ListAvailable -Name ImportExcel)

    if ($useExcel) {
        Import-Module ImportExcel -ErrorAction Stop

        # Cover
        $coverRows = @(
            [pscustomobject]@{ Field = 'TSC Revision'; Value = 'AICPA TSC 2017 (revised 2022)' }
            [pscustomobject]@{ Field = 'Type'; Value = 'Type 1' }
            [pscustomobject]@{ Field = 'Generated (UTC)'; Value = (Get-Date).ToUniversalTime().ToString('u') }
            [pscustomobject]@{ Field = 'Categories'; Value = (($catalog | Select-Object -ExpandProperty Family -Unique) -join ', ') }
            [pscustomobject]@{ Field = 'Total Controls'; Value = $summary.TotalControls }
            [pscustomobject]@{ Field = 'Total Findings'; Value = $summary.TotalFindings }
            [pscustomobject]@{ Field = 'Bundle Hash (SHA-256)'; Value = if ($evidence) { $evidence.BundleHash } else { '' } }
            [pscustomobject]@{ Field = 'Bundle Path'; Value = if ($evidence) { $evidence.Directory } else { '' } }
        )
        $coverRows | Export-Excel -Path $OutputPath -WorksheetName 'Cover' -AutoSize -ClearSheet

        # Summary by category
        $summaryRows = @()
        foreach ($family in @('CC', 'A', 'C', 'PI', 'P')) {
            $f = $summary.ByFamily[$family]
            if (-not $f) { continue }
            if (($f.Automated + $f.Manual) -eq 0) { continue }
            $summaryRows += [pscustomobject]@{
                Family = $family
                Automated = $f.Automated
                Manual = $f.Manual
                Pass = $f.Pass
                Fail = $f.Fail
                Warning = $f.Warning
                Info = $f.Info
            }
        }
        $summaryRows | Export-Excel -Path $OutputPath -WorksheetName 'Summary by Category' -AutoSize -TableName 'tblSummary'

        # Control register
        $registerRows = foreach ($control in $catalog) {
            [pscustomobject]@{
                ControlId = $control.Id
                Family = $control.Family
                FamilyName = $control.FamilyName
                Automation = $control.Automation
                Description = $control.Description
                ControlOwnerHint = $control.ControlOwnerHint
                FindingCount = if ($summary.ControlFindings.ContainsKey($control.Id)) { @($summary.ControlFindings[$control.Id]).Count } else { 0 }
            }
        }
        $registerRows | Export-Excel -Path $OutputPath -WorksheetName 'Control Register' -AutoSize -TableName 'tblRegister'

        # Findings sheets
        $sheetGroups = @{
            'Findings - CC6' = { param($c) $c.StartsWith('CC6') }
            'Findings - CC7' = { param($c) $c.StartsWith('CC7') }
            'Findings - CC8' = { param($c) $c.StartsWith('CC8') }
            'Findings - Other CC' = { param($c) $c.StartsWith('CC') -and -not ($c.StartsWith('CC6') -or $c.StartsWith('CC7') -or $c.StartsWith('CC8')) }
            'Findings - Availability' = { param($c) $c.StartsWith('A') }
            'Findings - Confidentiality' = { param($c) $c.StartsWith('C') -and -not $c.StartsWith('CC') }
        }

        foreach ($sheet in $sheetGroups.Keys) {
            $predicate = $sheetGroups[$sheet]
            $rows = foreach ($control in $catalog) {
                if (-not (& $predicate $control.Id)) { continue }
                $controlFindings = if ($summary.ControlFindings.ContainsKey($control.Id)) { @($summary.ControlFindings[$control.Id]) } else { @() }
                foreach ($finding in $controlFindings) {
                    [pscustomobject]@{
                        ControlId = $control.Id
                        Status = $finding.Status
                        Severity = if ($finding.PSObject.Properties['Severity']) { $finding.Severity } else { '' }
                        CheckName = $finding.CheckName
                        Object = $finding.Object
                        Description = $finding.Description
                        Remediation = $finding.Remediation
                    }
                }
            }
            if ($rows) {
                $rows | Export-Excel -Path $OutputPath -WorksheetName $sheet -AutoSize
            }
        }

        # Manual attestation register
        $manualRows = foreach ($control in $catalog) {
            if ($control.Automation -ne 'Manual') { continue }
            [pscustomobject]@{
                ControlId = $control.Id
                Family = $control.Family
                Description = $control.Description
                ControlOwner = ''
                DescriptionOfOperation = ''
                Frequency = ''
                EvidenceLocation = ''
                AttestedBy = ''
                AttestedDate = ''
            }
        }
        if ($manualRows) {
            $manualRows | Export-Excel -Path $OutputPath -WorksheetName 'Manual Attestation' -AutoSize -TableName 'tblManual'
        }

        # Evidence register
        if ($evidence -and (Test-Path -LiteralPath $evidence.ManifestPath)) {
            $manifest = Get-Content -LiteralPath $evidence.ManifestPath -Raw | ConvertFrom-Json
            $evidenceRows = foreach ($file in $manifest.Files) {
                [pscustomobject]@{
                    RelativePath = $file.RelativePath
                    SHA256 = $file.SHA256
                }
            }
            $evidenceRows | Export-Excel -Path $OutputPath -WorksheetName 'Evidence Register' -AutoSize -TableName 'tblEvidence'
        }

        return $OutputPath
    }

    # CSV fallback
    $csvDir = if ($OutputPath -like '*.xlsx') { [System.IO.Path]::ChangeExtension($OutputPath, '') -replace '\.$', '' } else { $OutputPath }
    if (-not (Test-Path -LiteralPath $csvDir)) {
        $null = New-Item -Path $csvDir -ItemType Directory -Force
    }

    # Cover
    @(
        [pscustomobject]@{ Field = 'TSC Revision'; Value = 'AICPA TSC 2017 (revised 2022)' }
        [pscustomobject]@{ Field = 'Generated (UTC)'; Value = (Get-Date).ToUniversalTime().ToString('u') }
        [pscustomobject]@{ Field = 'Total Controls'; Value = $summary.TotalControls }
        [pscustomobject]@{ Field = 'Total Findings'; Value = $summary.TotalFindings }
        [pscustomobject]@{ Field = 'Bundle Hash'; Value = if ($evidence) { $evidence.BundleHash } else { '' } }
    ) | Export-Csv -Path (Join-Path $csvDir '01-Cover.csv') -NoTypeInformation -Encoding UTF8

    # Control register
    $registerRows = foreach ($control in $catalog) {
        [pscustomobject]@{
            ControlId = $control.Id
            Family = $control.Family
            Automation = $control.Automation
            Description = $control.Description
            ControlOwnerHint = $control.ControlOwnerHint
            FindingCount = if ($summary.ControlFindings.ContainsKey($control.Id)) { @($summary.ControlFindings[$control.Id]).Count } else { 0 }
        }
    }
    $registerRows | Export-Csv -Path (Join-Path $csvDir '02-Control-Register.csv') -NoTypeInformation -Encoding UTF8

    # All findings flat
    $flatRows = foreach ($control in $catalog) {
        if (-not $summary.ControlFindings.ContainsKey($control.Id)) { continue }
        foreach ($finding in @($summary.ControlFindings[$control.Id])) {
            [pscustomobject]@{
                ControlId = $control.Id
                Family = $control.Family
                Status = $finding.Status
                Severity = if ($finding.PSObject.Properties['Severity']) { $finding.Severity } else { '' }
                CheckName = $finding.CheckName
                Object = $finding.Object
                Description = $finding.Description
                Remediation = $finding.Remediation
            }
        }
    }
    $flatRows | Export-Csv -Path (Join-Path $csvDir '03-Findings.csv') -NoTypeInformation -Encoding UTF8

    return $csvDir
}

#endregion

Export-ModuleMember -Function @(
    'New-SOC2AuditReport',
    'New-SOC2AuditWorkbook'
)
