<#
.SYNOPSIS
    EntraChecks-Branding.psm1 - Shared white-labeling helper for EntraChecks reports.

.DESCRIPTION
    Centralizes branding/customization concerns so any report module (SOC 2,
    unified, future) can render with consistent organization-specific look and
    feel.

    Reads configuration via the standard SOC2.Branding (or future top-level
    Branding) config block and produces a normalized "branding context" object
    used by HTML and Excel report builders.

    Validates that white-label runs include the minimum required organization
    metadata so we fail fast at config time instead of producing a half-branded
    artifact.

.NOTES
    Version: 1.0.0
    Author: EntraChecks Project
#>

#Requires -Version 5.1

$script:ModuleName = 'EntraChecks-Branding'
$script:ModuleVersion = '1.0.0'
$script:DefaultPrimaryColor = '#005A9E'

function Get-ReportBrandingContext {
    <#
    .SYNOPSIS
        Builds a normalized branding context for report rendering.

    .DESCRIPTION
        Accepts a branding config hashtable (typically SOC2.Branding from the
        loaded EntraChecks configuration) and returns a context object used by
        report builders. Encodes the organization logo as base64 once so report
        modules don't re-read it.

    .PARAMETER Config
        Branding configuration hashtable. Recognized keys:
        - WhiteLabel (bool)
        - OrganizationName (string)
        - OrganizationLogoPath (string, optional)
        - PrimaryColor (string, optional, hex)
        - ReportFooter (string, optional)
        - SuppressEntraChecksBranding (bool, optional)

    .PARAMETER ReportTitle
        Title to use when rendering report headers (e.g., "SOC 2 Internal Readiness Assessment").

    .OUTPUTS
        PSCustomObject suitable for direct injection into HTML/Excel templates.

    .EXAMPLE
        $branding = Get-ReportBrandingContext -Config $cfg.SOC2.Branding -ReportTitle 'SOC 2 Readiness'
    #>
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter()]
        [object]$Config,

        [Parameter(Mandatory)]
        [string]$ReportTitle
    )

    $whiteLabel = $false
    $orgName = ''
    $logoPath = ''
    $primaryColor = $script:DefaultPrimaryColor
    $footer = ''
    $suppressEntraBranding = $false

    if ($Config) {
        if ($Config.PSObject.Properties['WhiteLabel']) { $whiteLabel = [bool]$Config.WhiteLabel }
        elseif ($Config -is [hashtable] -and $Config.ContainsKey('WhiteLabel')) { $whiteLabel = [bool]$Config['WhiteLabel'] }

        $orgName = Get-BrandingValue -Config $Config -Key 'OrganizationName' -Default ''
        $logoPath = Get-BrandingValue -Config $Config -Key 'OrganizationLogoPath' -Default ''
        $cfgColor = Get-BrandingValue -Config $Config -Key 'PrimaryColor' -Default ''
        if (-not [string]::IsNullOrEmpty($cfgColor)) { $primaryColor = $cfgColor }
        $footer = Get-BrandingValue -Config $Config -Key 'ReportFooter' -Default ''
        $suppressEntraBranding = [bool](Get-BrandingValue -Config $Config -Key 'SuppressEntraChecksBranding' -Default $false)
    }

    if ($whiteLabel) {
        $validation = Test-BrandingConfiguration -Config $Config
        if (-not $validation.IsValid) {
            throw "Invalid white-label branding configuration: $($validation.Errors -join '; ')"
        }
    }

    $logoBase64 = ''
    $logoMimeType = ''
    if (-not [string]::IsNullOrEmpty($logoPath) -and (Test-Path -LiteralPath $logoPath)) {
        try {
            $bytes = [System.IO.File]::ReadAllBytes($logoPath)
            $logoBase64 = [System.Convert]::ToBase64String($bytes)
            $extension = [System.IO.Path]::GetExtension($logoPath).ToLowerInvariant()
            $logoMimeType = switch ($extension) {
                '.png' { 'image/png' }
                '.svg' { 'image/svg+xml' }
                '.jpg' { 'image/jpeg' }
                '.jpeg' { 'image/jpeg' }
                '.gif' { 'image/gif' }
                default { 'application/octet-stream' }
            }
        } catch {
            if (Get-Command Write-Log -ErrorAction SilentlyContinue) {
                Write-Log -Level WARN -Message "Could not load logo at ${logoPath}: $($_.Exception.Message)" -Category 'Branding'
            }
        }
    }

    $effectiveOrgName = if ($whiteLabel -or -not [string]::IsNullOrEmpty($orgName)) { $orgName } else { 'EntraChecks' }
    $effectiveAttribution = if ($suppressEntraBranding) { '' } else { "Generated by EntraChecks v$($script:ModuleVersion)" }

    return [pscustomobject]@{
        WhiteLabel = $whiteLabel
        ReportTitle = $ReportTitle
        OrganizationName = $effectiveOrgName
        LogoBase64 = $logoBase64
        LogoMimeType = $logoMimeType
        LogoDataUri = if ($logoBase64) { "data:$logoMimeType;base64,$logoBase64" } else { '' }
        PrimaryColor = $primaryColor
        Footer = $footer
        Attribution = $effectiveAttribution
        SuppressEntraChecksBranding = $suppressEntraBranding
    }
}

function Test-BrandingConfiguration {
    <#
    .SYNOPSIS
        Validates that a branding configuration is internally consistent.

    .DESCRIPTION
        When WhiteLabel is enabled, OrganizationName is required and the logo
        path (if specified) must resolve to an existing file. Returns a result
        object with IsValid and Errors fields so callers can fail fast.

    .PARAMETER Config
        The branding config hashtable / object to validate.

    .OUTPUTS
        PSCustomObject with IsValid (bool) and Errors (string[]).
    #>
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter()]
        [object]$Config
    )

    $errors = [System.Collections.Generic.List[string]]::new()

    if (-not $Config) {
        return [pscustomobject]@{ IsValid = $true; Errors = @() }
    }

    $whiteLabel = [bool](Get-BrandingValue -Config $Config -Key 'WhiteLabel' -Default $false)
    if ($whiteLabel) {
        $orgName = Get-BrandingValue -Config $Config -Key 'OrganizationName' -Default ''
        if ([string]::IsNullOrWhiteSpace($orgName)) {
            $errors.Add('Branding.OrganizationName is required when WhiteLabel = true.') | Out-Null
        }
    }

    $logoPath = Get-BrandingValue -Config $Config -Key 'OrganizationLogoPath' -Default ''
    if (-not [string]::IsNullOrEmpty($logoPath)) {
        if (-not (Test-Path -LiteralPath $logoPath)) {
            $errors.Add("Branding.OrganizationLogoPath does not exist: $logoPath") | Out-Null
        }
    }

    $color = Get-BrandingValue -Config $Config -Key 'PrimaryColor' -Default ''
    if (-not [string]::IsNullOrEmpty($color) -and ($color -notmatch '^#[0-9A-Fa-f]{6}$')) {
        $errors.Add("Branding.PrimaryColor must be a 6-digit hex color (e.g., '#005A9E'). Got: $color") | Out-Null
    }

    return [pscustomobject]@{
        IsValid = ($errors.Count -eq 0)
        Errors = $errors.ToArray()
    }
}

function Get-BrandingValue {
    <#
    .SYNOPSIS
        Internal helper: reads a branding config value from either a hashtable
        or a PSCustomObject.
    #>
    [CmdletBinding()]
    [OutputType([object])]
    param(
        [Parameter(Mandatory)][AllowNull()][object]$Config,
        [Parameter(Mandatory)][string]$Key,
        [Parameter()][object]$Default
    )

    if ($null -eq $Config) { return $Default }

    if ($Config -is [hashtable]) {
        if ($Config.ContainsKey($Key)) { return $Config[$Key] }
        return $Default
    }

    if ($Config.PSObject.Properties[$Key]) {
        return $Config.$Key
    }
    return $Default
}

Export-ModuleMember -Function @(
    'Get-ReportBrandingContext',
    'Test-BrandingConfiguration'
)
